version: '2'
services:
  web:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: "on-failure:3"
    depends_on:
      - db
  worker:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: bundle exec rake jobs:work
    depends_on:
      - web
  db:
    image: postgres:9.5
    env_file: .env
    volumes:
      - standup-app-postgres:/var/lib/postgresql/data
volumes:
  standup-app-postgres:
    driver: local
